#!/bin/bash
# Script para criar secret de autenticação no registry

set -euo pipefail

# Help
usage(){
    cat <<EOF 
Usage: $0 <username> <password> <email> [mgc_region] [secret_name]"
    <username>     Required. Usuário do Magalu Cloud Registry
    <password>     Required. Senha do Magalu Cloud Registry
    <email>        Required. Email do Magalu Cloud Registry
    [mgc_region]   Opcional. Região da MGC. Default: br-se1
                   Valores aceitos: br-se1, br-ne1
    [secret_name]  Opcional. Nome da secret a ser criada no Kubernetes
EOF
}

# --help ou -h
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

# Checa se o número de argumentos está correto
if [ "$#" -lt 3 ] || [ "$#" -gt 5 ]; then
    usage
    exit 1
fi

# Parâmetros
username=$1
password=$2
email=$3
mgc_region="${4:-br-se1}"
secret_name="${5:-magalu-registry-secret}"

# Valida mgc_region, se foi passado
allowed_regions=("br-se1" "br-ne1")
region_ok=false
for r in "${allowed_regions[@]}"; do
  if [[ "$mgc_region" == "$r" ]]; then
    region_ok=true
    break
  fi
done

if [[ "$region_ok" != "true" ]]; then
  echo "ERRO: mgc_region inválida: '${mgc_region}'."
  echo "Opções válidas: ${allowed_regions[*]}"
  usage
  exit 2
fi

# Cria a secret
kubectl create secret docker-registry $secret_name \
  --docker-server="https://container-registry.$mgc_region.magalu.cloud" \
  --docker-username=$username \
  --docker-password=$password \
  --docker-email=$email